"use client";
import { useRef, useState } from "react";
import { Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { analyzeAdsterraRoiAction } from "@/app/shopee/[id]/adsterra-roi/actions";
import type { AdsterraAnalysisConfig } from "@/lib/adsterra-roi/analyze";
import type { AdsterraRoiAnalysis } from "@/lib/adsterra-roi/types";
import { formatIdr, formatPercent, formatUsd } from "@/components/clickadu-roi/view-model";

type Result = { dateFrom: string; dateTill: string; fxRate: string; config: AdsterraAnalysisConfig; analysis: AdsterraRoiAnalysis };
export function AdsterraAnalysisWorkflow({ shopeeAccountId, shopeeAccountName, configs, connected }: { shopeeAccountId: number; shopeeAccountName: string; configs: AdsterraAnalysisConfig[]; connected: boolean }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<Result | null>(null); const lock = useRef(false);
  async function analyze(data: FormData) { if (lock.current) return; lock.current = true; setBusy(true); setError(""); setResult(null); try { const response = await analyzeAdsterraRoiAction(shopeeAccountId, data); if (response.success) setResult(response.result); else setError(response.message); } finally { lock.current = false; setBusy(false); } }
  return <section className="min-w-0 space-y-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div><h3 className="font-semibold">Analisa Adsterra ROI</h3><p className="text-sm text-slate-500">Read-only: statistik placement Adsterra dipadankan dengan Tag_link3 Shopee.</p></div>{!connected && <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Koneksi Adsterra belum dikonfigurasi.</p>}<form action={analyze} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><label className="text-sm font-medium">Campaign<select name="configId" required disabled={busy || !connected} className="mt-1 h-9 w-full rounded-lg border bg-white px-3"><option value="">Pilih campaign</option>{configs.map((config) => <option key={config.id} value={config.id}>{config.label || config.campaignId}</option>)}</select></label><label className="text-sm font-medium">Tanggal Mulai<input type="date" name="dateFrom" required className="mt-1 h-9 w-full rounded-lg border px-3"/></label><label className="text-sm font-medium">Tanggal Akhir<input type="date" name="dateTill" required className="mt-1 h-9 w-full rounded-lg border px-3"/></label><label className="text-sm font-medium">Kurs USD → IDR<input name="fxRate" defaultValue="16500" inputMode="decimal" required className="mt-1 h-9 w-full rounded-lg border px-3"/></label><label className="text-sm font-medium">CSV Komisi Shopee<input type="file" name="file" accept=".csv,text/csv,application/vnd.ms-excel" required className="mt-1 block max-w-full text-sm"/></label><Button disabled={busy || !connected || !configs.length}>{busy ? "Menganalisis..." : "Analisa"}</Button></form>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{result && <AnalysisResult result={result} shopeeName={shopeeAccountName}/>}</section>;
}

function AnalysisResult({ result, shopeeName }: { result: Result; shopeeName: string }) { const analysis = result.analysis; const clicks = analysis.rows.reduce((sum, row) => sum + row.clicks, 0); const stats = [["Biaya Iklan", formatIdr(analysis.totalCostIdr), formatUsd(analysis.totalSpentUsd)], ["Komisi Bersih Shopee", formatIdr(analysis.totalCommission), ""], ["Profit", formatIdr(analysis.totalProfit), ""], ["ROI", formatPercent(analysis.roi), ""], ["Klik Iklan", new Intl.NumberFormat("id-ID").format(clicks), ""], ["Kandidat Blacklist", String(analysis.candidatePlacements.length), "ROI < 30%"]]; return <div className="space-y-4"><div className="grid gap-1 rounded-lg border bg-slate-50 p-3 text-sm sm:grid-cols-2"><p>Shopee Account: <b>{shopeeName}</b></p><p>Campaign: <b>{result.config.label || result.config.campaignId}</b></p><p>Tag Link 1: <b>{result.config.sourceTag}</b></p><p>Periode: <b>{result.dateFrom} – {result.dateTill}</b></p><p>Kurs: <b>{formatIdr(result.fxRate)} / USD</b></p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{stats.map(([label, value, detail]) => <div key={label} className="rounded-lg border bg-slate-50 p-3"><p className="text-xs font-medium uppercase text-slate-500">{label}</p><p className="font-semibold">{value}</p>{detail && <p className="text-xs text-slate-500">{detail}</p>}</div>)}</div><div className="max-w-full overflow-x-auto rounded-lg border"><table className="w-full min-w-200 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Placement", "Spend USD", "Spend IDR", "Komisi", "Profit", "ROI", "Status"].map((label) => <th key={label} className="whitespace-nowrap px-3 py-3">{label}</th>)}</tr></thead><tbody className="divide-y">{analysis.rows.map((row) => <tr key={row.placement}><td className="px-3 py-3 font-medium">{row.placement}</td><td className="px-3 py-3">{formatUsd(row.spentUsd)}</td><td className="px-3 py-3">{formatIdr(row.costIdr)}</td><td className="px-3 py-3">{formatIdr(row.commission)}</td><td className={`px-3 py-3 ${row.profit.startsWith("-") ? "text-red-600" : "text-emerald-700"}`}>{formatIdr(row.profit)}</td><td className="px-3 py-3">{formatPercent(row.roi)}</td><td className={`whitespace-nowrap px-3 py-3 ${row.isBlacklistCandidate ? "text-red-600" : row.roi === null ? "text-slate-500" : "text-emerald-700"}`}>{row.isBlacklistCandidate ? "Kandidat Blacklist" : row.roi === null ? "Tanpa Biaya" : "Aman"}</td></tr>)}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3"><p className="break-words text-sm">{analysis.candidatePlacements.join(", ") || "Tidak ada kandidat Placement."}</p><Button type="button" variant="ghost" disabled={!analysis.candidatePlacements.length} onClick={() => navigator.clipboard.writeText(analysis.candidatePlacements.join(", "))}><Copy className="size-4"/>Copy Placement</Button></div></div>; }
