import Link from "next/link";
import { createMetaAccount } from "@/app/shopee/actions";
import { Button } from "@/components/ui/button";

type Option = { id: number; name: string; secondary: string };

export function MetaAccountForm({ businessManagers, shopeeAccounts, selectedShopeeAccountId }: { businessManagers: Option[]; shopeeAccounts: Option[]; selectedShopeeAccountId?: number }) {
  const cannotCreate = businessManagers.length === 0;
  return <form action={createMetaAccount} className="space-y-5 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div><p className="text-sm font-medium text-slate-500">Meta Account / WL</p><h2 className="mt-1 text-xl font-semibold text-slate-950">Tambah WL</h2></div>{cannotCreate && <p className="rounded-md bg-amber-50 p-3 text-sm text-amber-800">WL membutuhkan minimal satu Business Manager.</p>}<label className="block text-sm font-medium text-slate-700">Business Manager<select name="businessManagerId" required disabled={cannotCreate} className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm outline-none disabled:bg-slate-100"><option value="">Pilih Business Manager</option>{businessManagers.map((manager) => <option key={manager.id} value={manager.id}>{manager.name} — {manager.secondary}</option>)}</select></label><label className="block text-sm font-medium text-slate-700">Akun Shopee <span className="font-normal text-slate-400">(opsional)</span><select name="shopeeAccountId" disabled={cannotCreate} defaultValue={selectedShopeeAccountId ?? ""} className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm outline-none disabled:bg-slate-100"><option value="">Belum terhubung</option>{shopeeAccounts.map((account) => <option key={account.id} value={account.id}>{account.name}{account.secondary ? ` — ${account.secondary}` : ""}</option>)}</select></label><label className="block text-sm font-medium text-slate-700">Nama WL<input name="name" required disabled={cannotCreate} className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm outline-none disabled:bg-slate-100 focus:ring-2 focus:ring-slate-300" /></label><label className="block text-sm font-medium text-slate-700">Account ID<input name="accountId" required disabled={cannotCreate} className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm outline-none disabled:bg-slate-100 focus:ring-2 focus:ring-slate-300" /></label><label className="block text-sm font-medium text-slate-700">Status<select name="status" defaultValue="ACTIVE" disabled={cannotCreate} className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm outline-none disabled:bg-slate-100"><option value="ACTIVE">Aktif</option><option value="INACTIVE">Nonaktif</option></select></label><div className="flex justify-end gap-3"><Button asChild variant="ghost"><Link href={selectedShopeeAccountId ? `/shopee/${selectedShopeeAccountId}` : "/wl"}>Batal</Link></Button><Button type="submit" disabled={cannotCreate}>Simpan WL</Button></div></form>;
}
