"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "../../../../lib/auth/session";
import { prisma } from "../../../../lib/prisma";
import { TrafficProvider } from "../../../../lib/generated/prisma/client";
import { decryptTrafficSecret, encryptTrafficSecret } from "../../../../lib/traffic-credentials/crypto";
import { deleteTrafficCredential, getEncryptedTrafficCredential, saveTrafficCredential } from "../../../../lib/traffic-credentials/repository";
import { getAdsterraClient } from "../../../../lib/adsterra-roi/config";
import { buildAdsterraRoiAnalysis, AdsterraAnalysisError, publicAdsterraAnalysisMessage } from "../../../../lib/adsterra-roi/analyze";
import { AdsterraBlacklistError, replaceAdsterraBlacklist } from "../../../../lib/adsterra-roi/blacklist";
import { deleteAdsterraConfig, getAdsterraConfigById, saveAdsterraConfig } from "../../../../lib/adsterra-roi/config-repository";
import { publicAdsterraConfigMessage } from "../../../../lib/adsterra-roi/config-input";
import { readCsvUpload } from "../../../../lib/shopee-import/upload";
import { markBlacklistReplaced, runVerifiedBlacklistReplacement } from "../../../../lib/traffic-roi/replacement-timestamp";

export async function analyzeAdsterraRoiAction(shopeeAccountId: number, formData: FormData) { await requireUser(); try { const upload = await readCsvUpload(shopeeAccountId, formData); const result = await buildAdsterraRoiAnalysis({ shopeeAccountId, configId: formData.get("configId"), dateFrom: formData.get("dateFrom"), dateTill: formData.get("dateTill"), fxRate: formData.get("fxRate"), ...upload }, { loadConfig: (accountId, configId) => getAdsterraConfigById(prisma, accountId, configId), getStatistics: async (input) => { const credential = await getEncryptedTrafficCredential(prisma, shopeeAccountId, TrafficProvider.ADSTERRA); if (!credential) throw new AdsterraAnalysisError("Koneksi Adsterra belum dikonfigurasi."); return getAdsterraClient(decryptTrafficSecret(credential.encryptedSecret)).getPlacementStatistics(input); } }); return { success: true as const, result }; } catch (error) { return { success: false as const, message: publicAdsterraAnalysisMessage(error) }; } }
export async function replaceAdsterraBlacklistAction(shopeeAccountId: number, formData: FormData) { await requireUser(); try { const upload = await readCsvUpload(shopeeAccountId, formData); const credential = await getEncryptedTrafficCredential(prisma, shopeeAccountId, TrafficProvider.ADSTERRA); if (!credential) throw new AdsterraAnalysisError("Koneksi Adsterra belum dikonfigurasi."); const client = getAdsterraClient(decryptTrafficSecret(credential.encryptedSecret)); const analysis = await buildAdsterraRoiAnalysis({ shopeeAccountId, configId: formData.get("configId"), dateFrom: formData.get("dateFrom"), dateTill: formData.get("dateTill"), fxRate: formData.get("fxRate"), ...upload }, { loadConfig: (accountId, configId) => getAdsterraConfigById(prisma, accountId, configId), getStatistics: (input) => client.getPlacementStatistics(input) }); const replacement = await runVerifiedBlacklistReplacement(() => replaceAdsterraBlacklist(analysis.config.campaignId, analysis.analysis.rows, client), (at) => markBlacklistReplaced(prisma, "ADSTERRA", shopeeAccountId, analysis.config.id, at)); if (replacement.status === "UPDATED") revalidatePath(`/shopee/${shopeeAccountId}/adsterra-roi`); return { success: true as const, status: replacement.status, finalCount: replacement.targetPlacementIds.length, addedCount: replacement.addedPlacementIds.length, removedCount: replacement.removedPlacementIds.length, preservedWithoutDataCount: replacement.preservedWithoutDataPlacementIds.length, lastBlacklistReplacedAt: replacement.lastBlacklistReplacedAt }; } catch (error) { return { success: false as const, message: error instanceof AdsterraBlacklistError ? error.message : publicAdsterraAnalysisMessage(error) }; } }
export async function saveAdsterraCredentialAction(shopeeAccountId: number, formData: FormData) { await requireUser(); try { const key = formData.get("apiKey"); if (typeof key !== "string" || !key.trim()) return { success: false as const, message: "API Key wajib diisi." }; await saveTrafficCredential(prisma, shopeeAccountId, TrafficProvider.ADSTERRA, encryptTrafficSecret(key.trim())); revalidatePath(`/shopee/${shopeeAccountId}/adsterra-roi`); return { success: true as const }; } catch { return { success: false as const, message: "Gagal menyimpan koneksi Adsterra." }; } }
export async function deleteAdsterraCredentialAction(shopeeAccountId: number) { await requireUser(); try { if (!await deleteTrafficCredential(prisma, shopeeAccountId, TrafficProvider.ADSTERRA)) return { success: false as const, message: "Koneksi Adsterra tidak ditemukan." }; revalidatePath(`/shopee/${shopeeAccountId}/adsterra-roi`); return { success: true as const }; } catch { return { success: false as const, message: "Gagal memutuskan koneksi Adsterra." }; } }
export async function saveAdsterraConfigAction(shopeeAccountId: number, formData: FormData) { await requireUser(); try { await saveAdsterraConfig(prisma, shopeeAccountId, { id: formData.get("configId") || undefined, campaignId: formData.get("campaignId"), label: formData.get("label"), sourceTag: formData.get("sourceTag") }); revalidatePath(`/shopee/${shopeeAccountId}/adsterra-roi`); return { success: true as const }; } catch (error) { return { success: false as const, message: publicAdsterraConfigMessage(error) }; } }
export async function deleteAdsterraConfigAction(shopeeAccountId: number, configId: number) { await requireUser(); try { await deleteAdsterraConfig(prisma, shopeeAccountId, configId); revalidatePath(`/shopee/${shopeeAccountId}/adsterra-roi`); return { success: true as const }; } catch (error) { return { success: false as const, message: publicAdsterraConfigMessage(error) }; } }
