import Link from "next/link";
import { dashboardParamsToSearch, withDashboardAccountChange, type DashboardParams, type DashboardSortKey } from "@/lib/dashboard/params";
import type { DashboardAccountData } from "@/lib/dashboard/queries";
import { formatRupiah } from "@/lib/filter/table-utils";
import { DashboardPageSizeSelect } from "./dashboard-page-size-select";

const columns: { key: DashboardSortKey; label: string }[] = [{ key: "date", label: "Tanggal" }, { key: "budget", label: "Spend" }, { key: "costWithFee", label: "+5%" }, { key: "commission", label: "Komisi" }, { key: "profit", label: "Profit" }, { key: "profitPercent", label: "% Profit" }];
const dateFormatter = new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" });
const percent = (value: number | null) => value === null ? "—" : `${value.toFixed(2)}%`;
const date = (value: string) => dateFormatter.format(new Date(`${value}T00:00:00.000Z`));
const tone = (value: number | null) => value === null ? "text-slate-950" : value < 0 ? "text-red-600" : value > 0 ? "text-emerald-600" : "text-slate-950";

function href(state: DashboardParams, accountId: number, change: Parameters<typeof withDashboardAccountChange>[2]) { return `?${dashboardParamsToSearch(withDashboardAccountChange(state, accountId, change))}`; }

export function ShopeePerformanceCard({ account, dashboardState }: { account: DashboardAccountData; dashboardState: DashboardParams }) {
  const stats = [["Total Spend", formatRupiah(account.summary.budget)], ["+5%", formatRupiah(account.summary.costWithFee)], ["Komisi", formatRupiah(account.summary.commission)], ["Profit", formatRupiah(account.summary.profit)], ["% Profit", percent(account.summary.profitPercent)]];
  return <article className="min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
    <header className="border-b border-slate-200 p-4 sm:p-6"><h2 className="break-words text-xl font-semibold tracking-tight text-slate-950">{account.name}</h2><p className="mt-1 text-sm text-slate-500">{account.wlCount} WL terhubung</p><dl className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{stats.map(([label, value], index) => <div key={label} className="min-w-0 rounded-lg border border-slate-200 bg-slate-50/70 p-3"><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</dt><dd className={`mt-1 break-words text-base font-semibold ${index >= 3 ? tone(index === 3 ? account.summary.profit : account.summary.profitPercent) : "text-slate-950"}`}>{value}</dd></div>)}</dl></header>
    <div className="max-w-full overflow-x-auto overscroll-x-contain"><table className="w-full min-w-175 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{columns.map((column) => { const active = account.state.sort === column.key; const dir = active && account.state.dir === "asc" ? "desc" : "asc"; return <th key={column.key} className="px-3 py-3 font-medium sm:px-4"><Link href={href(dashboardState, account.id, { sort: column.key, dir })} className="inline-flex items-center gap-1 whitespace-nowrap">{column.label}<span aria-hidden="true">{active ? account.state.dir === "asc" ? "↑" : "↓" : "↕"}</span></Link></th>; })}</tr></thead><tbody className="divide-y divide-slate-200">{account.days.map((row) => <tr key={row.date}><td className="whitespace-nowrap px-3 py-3 font-medium text-slate-950 sm:px-4">{date(row.date)}</td><td className="whitespace-nowrap px-3 py-3 sm:px-4">{formatRupiah(row.budget)}</td><td className="whitespace-nowrap px-3 py-3 sm:px-4">{formatRupiah(row.costWithFee)}</td><td className="whitespace-nowrap px-3 py-3 sm:px-4">{formatRupiah(row.commission)}</td><td className={`whitespace-nowrap px-3 py-3 sm:px-4 ${tone(row.profit)}`}>{formatRupiah(row.profit)}</td><td className={`whitespace-nowrap px-3 py-3 sm:px-4 ${tone(row.profitPercent)}`}>{percent(row.profitPercent)}</td></tr>)}{account.days.length === 0 && <tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500">Belum ada histori dalam rentang tanggal ini.</td></tr>}</tbody></table></div>
    <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 px-3 py-3 text-sm text-slate-600 sm:px-4"><span>{account.pagination.total} tanggal · Halaman {account.pagination.page} dari {account.pagination.pageCount}</span><div className="flex w-full flex-wrap items-center gap-2 sm:w-auto"><label className="flex items-center gap-2">Baris <DashboardPageSizeSelect value={account.pagination.pageSize} hrefs={Object.fromEntries([25,50,100].map((size) => [size, href(dashboardState, account.id, { pageSize: size as 25 | 50 | 100 })]))}/></label><Link aria-disabled={account.pagination.page <= 1} href={account.pagination.page <= 1 ? "#" : href(dashboardState, account.id, { page: account.pagination.page - 1 })} className={`rounded-md border border-slate-300 px-3 py-1 ${account.pagination.page <= 1 ? "pointer-events-none opacity-40" : ""}`}>Sebelumnya</Link><Link aria-disabled={account.pagination.page >= account.pagination.pageCount} href={account.pagination.page >= account.pagination.pageCount ? "#" : href(dashboardState, account.id, { page: account.pagination.page + 1 })} className={`rounded-md border border-slate-300 px-3 py-1 ${account.pagination.page >= account.pagination.pageCount ? "pointer-events-none opacity-40" : ""}`}>Berikutnya</Link></div></footer>
  </article>;
}
