import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import "dotenv/config";
import { PrismaClient } from "../generated/prisma/client.ts";
import { loadShopeeCampaignCandidates } from "./campaign-repository.ts";
import { importShopeeCommissions } from "./importer.ts";
import { lockShopeeAccount, persistCommissionImportInTransaction } from "./persistence.ts";
import { buildShopeeCommissionPreview } from "./preview.ts";
const prisma = new PrismaClient(); class Rollback extends Error {}
test("TERRA import replaces commission, preserves spend, and shares the atomic Meta transaction", async () => { const account = await prisma.shopeeAccount.findFirst({ where: { metaAccounts: { some: {} } }, select: { id: true, metaAccounts: { take: 1, select: { id: true } } } }); assert.ok(account); await assert.rejects(prisma.$transaction(async (tx) => { const suffix = randomUUID().replaceAll("-", "").slice(0, 8).toUpperCase(); const sourceTag = `TERRA${suffix}`; const campaign = await tx.campaign.create({ data: { metaCampaignId: `terra-${randomUUID()}`, name: `META-${suffix}`, budgetSource: "UNRESOLVED", metaAccountId: account.metaAccounts[0].id } }); const config = await tx.adsterraCampaignConfig.create({ data: { shopeeAccountId: account.id, campaignId: `adsterra-${suffix}`, sourceTag } }); await tx.adsterraCampaignDailyMetric.create({ data: { adsterraCampaignConfigId: config.id, date: new Date("2026-09-18T00:00:00Z"), spendUsd: "2.5" } }); const csv = new TextEncoder().encode(`Waktu Pemesanan,Tag_link1,Tag_link2,Tag_link3,Komisi Bersih Affiliate (Rp)\n2026-09-18 10:00:00,${sourceTag},${campaign.name},101,100.125\n2026-09-18 11:00:00,${sourceTag.toLowerCase()},${campaign.name},102,200.375\n2026-09-19 10:00:00,${sourceTag},${campaign.name},103,50`); const candidates = await loadShopeeCampaignCandidates(tx, account.id); const preview = await buildShopeeCommissionPreview({ shopeeAccountId: account.id, originalFilename: "terra.csv", bytes: csv }, { accountExists: async () => true, loadCampaigns: async () => candidates }); const deps = { withTransaction: async (work) => work(tx), lockAccount: lockShopeeAccount, loadCampaigns: loadShopeeCampaignCandidates, loadClickaduConfigs: async () => [], loadAdsterraConfigs: (db, id) => db.adsterraCampaignConfig.findMany({ where: { shopeeAccountId: id }, select: { id: true, sourceTag: true } }), persist: persistCommissionImportInTransaction }; await importShopeeCommissions({ shopeeAccountId: account.id, originalFilename: "terra.csv", bytes: csv, confirmation: preview.confirmation }, deps); await importShopeeCommissions({ shopeeAccountId: account.id, originalFilename: "terra.csv", bytes: csv, confirmation: preview.confirmation }, deps); const first = await tx.adsterraCampaignDailyMetric.findUniqueOrThrow({ where: { adsterraCampaignConfigId_date: { adsterraCampaignConfigId: config.id, date: new Date("2026-09-18T00:00:00Z") } } }); assert.equal(first.commissionIdr?.toFixed(5), "300.50000"); assert.equal(first.spendUsd?.toFixed(6), "2.500000"); const commissionOnly = await tx.adsterraCampaignDailyMetric.findUniqueOrThrow({ where: { adsterraCampaignConfigId_date: { adsterraCampaignConfigId: config.id, date: new Date("2026-09-19T00:00:00Z") } } }); assert.equal(commissionOnly.commissionIdr?.toFixed(5), "50.00000"); assert.equal(commissionOnly.spendUsd, null); throw new Rollback(); }, { timeout: 30_000 }), Rollback); });
test.after(async () => prisma.$disconnect());
