"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { importReasonLabel } from "./view-model";
import { importShopeeClickAction, previewShopeeClickAction } from "@/app/shopee/[id]/import/actions";
import type { ClickHistoryRow, ClickImportReceipt, ClickPreview } from "@/lib/shopee-click-import/types";
import type { HistoryPageInfo, ImportHistoryParams } from "@/lib/shopee-import/history-pagination";
import { ImportHistoryPagination } from "./history-pagination";

const range = (from: string, to: string) => from === to ? from : `${from} – ${to}`;
function ClickPreviewSummary({ preview }: { preview: ClickPreview }) { const items = [["File", preview.originalFilename], ["Periode", range(preview.dateFrom, preview.dateTo)], ["Logical rows", preview.csvRowCount], ["Rows META", preview.processedRowCount], ["Groups", preview.groupCount], ["Matched", preview.matchedCount], ["Unmatched", preview.unmatchedCount], ["Ignored", preview.ignoredRowCount], ["Matched clicks", preview.matchedClicks], ["Unmatched clicks", preview.unmatchedClicks]]; return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{items.map(([label, value]) => <div key={label} className="rounded-lg border border-slate-200 p-3"><p className="text-xs font-medium uppercase text-slate-500">{label}</p><p className="mt-1 break-words font-medium text-slate-900">{value}</p></div>)}</div>; }
function ClickHistory({ rows }: { rows: ClickHistoryRow[] }) { if (!rows.length) return <p className="p-6 text-sm text-slate-500">Belum ada riwayat import klik.</p>; return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Waktu", "File", "Periode", "Rows", "META", "Ignored", "Matched", "Unmatched"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row) => <tr key={row.id}><td className="px-4 py-3">{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short" }).format(new Date(row.createdAt))}</td><td className="px-4 py-3 font-medium">{row.originalFilename}</td><td className="px-4 py-3">{range(row.dateFrom, row.dateTo)}</td><td className="px-4 py-3">{row.csvRowCount}</td><td className="px-4 py-3">{row.processedRowCount}</td><td className="px-4 py-3">{row.ignoredRowCount}</td><td className="px-4 py-3">{row.matchedClicks}</td><td className="px-4 py-3">{row.unmatchedClicks}</td></tr>)}</tbody></table></div>; }

export function ClickImportWorkflow({ shopeeAccountId, history, historyPagination, historyState }: { shopeeAccountId: number; history: ClickHistoryRow[]; historyPagination: HistoryPageInfo; historyState: ImportHistoryParams }) {
  const router = useRouter(); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<ClickPreview | null>(null); const [receipt, setReceipt] = useState<ClickImportReceipt | null>(null); const [error, setError] = useState(""); const [phase, setPhase] = useState<"idle" | "preview" | "import">("idle"); const busy = phase !== "idle";
  async function runPreview() { if (!file) return; setPhase("preview"); setError(""); setReceipt(null); const form = new FormData(); form.set("file", file); const result = await previewShopeeClickAction(shopeeAccountId, form); if (result.success) setPreview(result.preview); else { setPreview(null); setError(result.message); } setPhase("idle"); }
  async function runImport() { if (!file || !preview) return; setPhase("import"); setError(""); const form = new FormData(); form.set("file", file); const result = await importShopeeClickAction(shopeeAccountId, preview.confirmation, form); if (result.success) { setReceipt(result.receipt); setPreview(null); router.refresh(); } else setError(result.message.includes("Preview") || result.message.includes("File berubah") ? `${result.message} Silakan Preview ulang.` : result.message); setPhase("idle"); }
  return <section className="space-y-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div><h3 className="font-semibold text-slate-950">Import Klik Shopee</h3><p className="mt-1 text-sm text-slate-500">Impor klik harian dari Tag_link dengan Tag Link 1 META.</p></div><div className="flex flex-wrap items-center gap-3"><input aria-label="File CSV Klik Shopee" type="file" accept=".csv,text/csv,application/vnd.ms-excel" disabled={busy} onChange={(event) => { setFile(event.target.files?.[0] ?? null); setPreview(null); setReceipt(null); setError(""); }} className="block text-sm"/><Button disabled={busy || !file} onClick={runPreview}>{phase === "preview" ? "Memproses…" : "Preview Klik"}</Button></div>{error && <div role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}{preview && <div className="space-y-4"><ClickPreviewSummary preview={preview}/><div><h4 className="mb-2 font-medium">Unmatched</h4>{preview.unmatched.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Tanggal", "Tag Link 2", "Reason", "Click count"].map((label) => <th key={label} className="px-3 py-2">{label}</th>)}</tr></thead><tbody>{preview.unmatched.map((row) => <tr key={`${row.date}-${row.tagLink2}`}><td className="px-3 py-2">{row.date}</td><td className="px-3 py-2">{row.tagLink2}</td><td className="px-3 py-2">{importReasonLabel(row.reason)}</td><td className="px-3 py-2">{row.clickCount}</td></tr>)}</tbody></table></div> : <p className="text-sm text-slate-500">Semua group berhasil dicocokkan.</p>}</div><Button disabled={busy} onClick={runImport}>{phase === "import" ? "Mengimpor…" : "Import Klik Sekarang"}</Button></div>}{receipt && <div className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Import berhasil: {receipt.matchedClicks} klik matched, {receipt.unmatchedClicks} klik unmatched.</div>}<div className="-mx-6 -mb-6 mt-6 border-t"><h4 className="px-6 py-4 font-semibold">Riwayat Import Klik</h4><ClickHistory rows={history}/><ImportHistoryPagination kind="click" pagination={historyPagination} state={historyState}/></div></section>;
}
