import Link from "next/link";
import { StatusBadge } from "@/components/shopee/status-badge";
import { Button } from "@/components/ui/button";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export default async function ShopeePage() {
  const shopeeAccounts = await prisma.shopeeAccount.findMany({ include: { _count: { select: { metaAccounts: true } } }, orderBy: { name: "asc" } });
  return <section className="min-w-0 space-y-6"><div className="flex min-w-0 flex-wrap items-center justify-between gap-4"><div className="min-w-0"><p className="text-sm font-medium text-slate-500">Master data</p><h2 className="break-words text-2xl font-semibold tracking-tight text-slate-950">Akun Shopee</h2></div><Button asChild><Link href="/shopee/new">Tambah Akun</Link></Button></div>{shopeeAccounts.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-5 text-center text-sm text-slate-500 sm:p-8">Belum ada Akun Shopee. Tambahkan akun pertama untuk mulai mengelola WL.</div> : <div className="min-w-0 max-w-full overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="max-w-full overflow-x-auto overscroll-x-contain"><table className="w-full min-w-150 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3 font-medium sm:px-6">Nama Akun</th><th className="px-3 py-3 font-medium sm:px-6">Jumlah WL</th><th className="px-3 py-3 font-medium sm:px-6">Status</th><th className="px-3 py-3 sm:px-6"><span className="sr-only">Detail</span></th></tr></thead><tbody className="divide-y divide-slate-200">{shopeeAccounts.map((account) => <tr key={account.id}><td className="max-w-64 truncate px-3 py-4 font-medium text-slate-900 sm:px-6" title={account.name}>{account.name}</td><td className="px-3 py-4 text-slate-600 sm:px-6">{account._count.metaAccounts}</td><td className="px-3 py-4 sm:px-6"><StatusBadge status={account.status} /></td><td className="px-3 py-4 text-right sm:px-6"><Link href={`/shopee/${account.id}`} className="font-medium text-slate-900 hover:underline">Lihat detail</Link></td></tr>)}</tbody></table></div></div>}</section>;
}
