"use client";

import { useState } from "react";
import { analyzeClickaduRoiAction } from "@/app/shopee/[id]/clickadu-roi/actions";
import { Button } from "@/components/ui/button";
import type { ClickaduAnalysisConfig, ClickaduAnalysisResult } from "@/lib/clickadu-roi/analyze";
import { AnalysisSummary } from "./analysis-summary";
import { CopyCandidatesButton } from "./copy-candidates-button";
import { ZoneTable } from "./zone-table";
import { formatAnalysisDate } from "./view-model";

export function ClickaduAnalysisWorkflow({ shopeeAccountId, shopeeAccountName, configs, connected }: { shopeeAccountId: number; shopeeAccountName: string; configs: ClickaduAnalysisConfig[]; connected: boolean }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<ClickaduAnalysisResult | null>(null);
  async function run(formData: FormData) { setBusy(true); setError(""); setResult(null); const response = await analyzeClickaduRoiAction(shopeeAccountId, formData); setBusy(false); if (response.success) setResult(response.analysis); else setError(response.message); }
  return <section className="min-w-0 space-y-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div><h3 className="font-semibold text-slate-950">Analisa Clickadu ROI</h3><p className="mt-1 text-sm text-slate-500">Analisis read-only berdasarkan statistik Clickadu dan CSV Shopee.</p></div>
    {!connected && <div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Koneksi Clickadu belum dikonfigurasi.</div>}
    <form action={run} className="grid items-start gap-3 sm:grid-cols-2 xl:grid-cols-5"><label className="text-sm font-medium text-slate-700">Campaign Clickadu<select name="configId" required disabled={busy || !configs.length || !connected} className="mt-1 h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-normal"><option value="">Pilih campaign</option>{configs.map((config) => <option key={config.id} value={config.id}>{config.label || config.campaignId}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Tanggal Mulai<input type="date" name="dateFrom" required className="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3 text-sm font-normal"/></label><label className="text-sm font-medium text-slate-700">Tanggal Akhir<input type="date" name="dateTill" required className="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3 text-sm font-normal"/></label><label className="text-sm font-medium text-slate-700">Kurs USD → IDR<input name="fxRate" inputMode="decimal" defaultValue="16500" required className="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3 text-sm font-normal"/></label><label className="min-w-0 text-sm font-medium text-slate-700">CSV Komisi Shopee<input type="file" name="file" accept=".csv,text/csv,application/vnd.ms-excel" required className="mt-1 block min-w-0 max-w-full text-sm font-normal"/><span className="mt-1 block text-xs font-normal text-slate-500">Gunakan CSV Shopee dengan periode yang sama.</span></label><Button className="sm:col-span-2 xl:col-span-1" disabled={busy || !configs.length || !connected}>{busy ? "Menganalisa…" : "Analisa"}</Button></form>
    {error && <div role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {result && <div className="space-y-4"><div className="grid gap-1 rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm text-slate-600 sm:grid-cols-2"><p>Campaign Clickadu: <span className="font-medium text-slate-900">{result.config.label || result.config.campaignId}</span></p><p>Shopee: <span className="font-medium text-slate-900">{shopeeAccountName}</span></p><p>Tag_link1: <span className="font-medium text-slate-900">{result.config.sourceTag}</span></p><p>Periode: <span className="font-medium text-slate-900">{formatAnalysisDate(result.dateFrom)} – {formatAnalysisDate(result.dateTill)}</span></p></div><div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-slate-700"><p className="font-medium text-slate-900">Aturan Kandidat Blacklist</p><p className="mt-1">Zone menjadi Kandidat Blacklist jika Biaya Iklan &gt; Rp0 dan ROI &lt; 30%.</p><p>ROI ≥ 30% dianggap aman/profitable.</p><p className="mt-1 text-slate-600">Status ini hanya rekomendasi analisa. Business Tracker belum mengubah blacklist Clickadu secara otomatis.</p></div><AnalysisSummary analysis={result.analysis}/><ZoneTable analysis={result.analysis}/><div className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">Zone Candidate Blacklist</p><p className="mt-1 break-words text-sm text-slate-600">{result.analysis.candidateZones.join(", ") || "Tidak ada kandidat."}</p></div><CopyCandidatesButton zones={result.analysis.candidateZones}/></div></div></div>}
  </section>;
}
