import { Prisma, type PrismaClient } from "../generated/prisma/client.ts";
import { calculateAdsterraDailyFinancials } from "./financials.ts";
import type { AdsterraHistoryParams, AdsterraHistorySortKey } from "./server-pagination.ts";
type Db = Pick<PrismaClient, "adsterraCampaignConfig" | "adsterraCampaignDailyMetric" | "$queryRaw">;
type Row = { id: number; date: Date; spendUsd: Prisma.Decimal | null; commissionIdr: Prisma.Decimal | null };
const columns: Record<AdsterraHistorySortKey, string> = { date: "metric.date", spendUsd: "metric.spendUsd", spendIdr: "metric.spendUsd * 19000", commission: "metric.commissionIdr", profit: "metric.commissionIdr - metric.spendUsd * 19000" };
export async function getAdsterraDailySyncConfigs(db: Pick<PrismaClient, "adsterraCampaignConfig">, shopeeAccountId: number) { const rows = await db.adsterraCampaignConfig.findMany({ where: { shopeeAccountId }, select: { id: true, campaignId: true, historySyncedThrough: true, dailyMetrics: { select: { date: true }, orderBy: { date: "desc" }, take: 1 } }, orderBy: { id: "asc" } }); return rows.map((x) => ({ id: x.id, campaignId: x.campaignId, historySyncedThrough: x.historySyncedThrough?.toISOString().slice(0, 10) ?? null, latestMetricDate: x.dailyMetrics[0]?.date.toISOString().slice(0, 10) ?? null })); }
export async function getAdsterraCampaignList(db: Pick<PrismaClient, "adsterraCampaignConfig">, shopeeAccountId: number) { return db.adsterraCampaignConfig.findMany({ where: { shopeeAccountId }, select: { id: true, campaignId: true, label: true, sourceTag: true, lastBlacklistReplacedAt: true }, orderBy: [{ label: "asc" }, { id: "asc" }] }); }
export async function getAdsterraDailyHistory(db: Db, shopeeAccountId: number, configId: number, params: AdsterraHistoryParams) { if (![shopeeAccountId, configId].every((x) => Number.isSafeInteger(x) && x > 0)) return null; const config = await db.adsterraCampaignConfig.findFirst({ where: { id: configId, shopeeAccountId }, select: { id: true, campaignId: true, label: true, sourceTag: true } }); if (!config) return null; const total = await db.adsterraCampaignDailyMetric.count({ where: { adsterraCampaignConfigId: config.id } }); const pageCount = Math.max(1, Math.ceil(total / params.pageSize)); const page = Math.min(Math.max(1, params.page), pageCount); const column = Prisma.raw(columns[params.sort]); const direction = Prisma.raw(params.dir === "asc" ? "ASC" : "DESC"); const rows = await db.$queryRaw<Row[]>(Prisma.sql`SELECT metric.id, metric.date, metric.spendUsd, metric.commissionIdr FROM AdsterraCampaignDailyMetric metric WHERE metric.adsterraCampaignConfigId = ${config.id} ORDER BY ${column} IS NULL ASC, ${column} ${direction}, metric.date DESC, metric.id ASC LIMIT ${params.pageSize} OFFSET ${(page - 1) * params.pageSize}`); return { config, rows: rows.map((row) => ({ id: row.id, date: row.date.toISOString().slice(0, 10), spendUsd: row.spendUsd?.toString() ?? null, commissionIdr: row.commissionIdr?.toString() ?? null, ...calculateAdsterraDailyFinancials(row.spendUsd?.toString() ?? null, row.commissionIdr?.toString() ?? null) })), pagination: { page, pageSize: params.pageSize, total, pageCount }, state: { ...params, page } }; }
export type AdsterraDailyHistory = NonNullable<Awaited<ReturnType<typeof getAdsterraDailyHistory>>>;
